### ISSUE TITLE
A little bug in Hamiltonian-Monte-Carlo code

### ISSUE THREAD

**Issue by Mizersy** [bocaiwen/bocaiwen.github.io#2]
Thanks for the brillant blog about Hamiltonian-Monte-Carlo, it really helps me a lot. But there is a little bug in the code, when we decide whether accept the new (z,r), you compare random.random() with torch.exp(nH - oH). We should compare random.random() with torch.exp(oH-nH), as p(z,r) = 1/Z_H*Exp(-H(z,r)). p(zn,rn)/p(z0,r0) = (1/Z_H*Exp(-H(zn,rn)))/(1/Z_H*Exp(-H(z0,r0)))=Exp(H(z0,r0))-H(zn,rn))

**Comment by bocaiwen** [comment]
Thanks for pointing out this bug.
I have fixed it and pushed the code.

**Comment by bocaiwen** [comment]
fixed
